### PR TITLE
Add Memoization, deltaE distance support

### PR DESCRIPTION
**Pull request by johnmerchant**
Greetings, I have added 2 features to this module

* Added memoization / caching, resulting in a noticeable performance improvement
* Optionally allow for using the [Delta-E](http://zschuessler.github.io/DeltaE/learn/) function for color distance

### CODE REVIEW

**Comment by zeke** [comment]
Thanks for this contribution, and sorry for the delay reviewing this!

It looks like CI is failing because we're targeting older versions of Node.js. Can you update the `.travis.yml` config to target some newer version(s), like 8, 10, and 12? See https://github.com/nodejs/Release

**Comment by johnmerchant** [comment]
I have updated the CI config to use the latest releases of Node.js 8, 10 and 12

**Comment by johnmerchant** [comment]
Should we also ensure the package's [engines](https://docs.npmjs.com/files/package.json#engines) match what versions are tested against on CI?

**Comment by zeke** [comment]
This is fantastic! Didn't know about deltaE.  ✨🌈 📐✨

Thanks for the contribution, @jmercha 

```
~/git/colorjs/color-namer master
$ np minor

Publish a new version of color-namer (current: 1.3.0)

Commits:
- update gitignore  ad83ef8
- Merge pull request #9 from jmercha/master  8cfee98
- Update CI  b4fc3bb
- Downgrade mocha  a980e46
- Fix test  13249f8
- Update docs  2114934
- Preparing pull request  5a6ecae
- del semi  5f91f52
- Use delta E distance in tests, add mocha, fix memo  1fd76ce
- Add memoization, use deltaE  1201d45
- update repository url  c83f32e

Commit Range:
v1.3.0...master


  ✔ Prerequisite check
  ✔ Git
  ↓ Cleanup [skipped]
  ✔ Installing dependencies using npm
  ✔ Running tests using npm
  ✔ Bumping version using npm
  ✔ Publishing package using npm
  ✔ Pushing tags
  ✔ Creating release draft on GitHub

 color-namer 1.4.0 published 🎉
```

**Pull request merged**
